server:
    port: 8000
    servlet:
        context-path: /api
    tomcat:
        basedir: "tomcat"
        accesslog:
            enabled: true
            directory: access

spring:
    application:
        name: COVID-19
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/covid19_db?useUnicode=yes&characterEncoding=UTF-8
        username: root
        password: root
        hikari.maximumPoolSize: 25
    idhs:
        url: http://43.224.124.234:7080/api
        username: dev
        password: Dev12345#
    pid:
        file: application.pid
    portal:
        userCredentials:
        - [dev, dev]
        - [dev2@aaa.com, dev]
    googleapi:
        mapKey: abc
    session:
        timeout: 3600
        jdbc:
            initialize-schema: always
            schema: classpath:session/schema-mysql.sql
            initializer:
                enabled: true

firebase:
    config-path: credentials/covid-19-lk-dev-firebase-adminsdk.json
    topic: 'mobile_message' #use mobile_message_test for test env

webapp:
    war:
        filename: portal-frontend.war
        context: ''
